### ISSUE TITLE
Twitterify extension error on Monterey Beta 

### ISSUE THREAD

**Issue by seishonagon** [ttscoff/popclipextensions#10]
oops, this one I don't know enough ruby to fix. 
When installing Twitterify on my M1 Mac mini running Monterey 12.0 Beta (21A5534d) I get this:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/6635078/136734648-034bc01c-6924-49df-9cd1-c989722aa193.png">

**Comment by ttscoff** [comment]
Not ruby (or Monterey), looks like I had some bad XML in some of the config plist files. Pushed a new version to this repo, and an zipped download with the update (v1.34) will be [on my blog](https://brettterpstra.com/projects/bretts-popclip-extensions/) shortly.
