### ISSUE TITLE
LinkCleaner not cleaning...

### ISSUE THREAD

**Issue by golflabel** [ttscoff/popclipextensions#7]
Maybe I'm doing something wrong, or expecting it to do more than it was designed to do, but LinkCleaner doesn't seem to be working for me.

I've got this link: https://clutchpoints.com/clippers-news-rajon-rondo-speaks-out-after-clippers-debut-vs-lakers/?fbclid=IwAR3epED82RKaRTrmL4X_uBCoVjU6mmFxFhZcAXshKwMzm17RuAT_oxxteiE – and when I clean it, it stays the same. 

I imagined it'd clean to: "https://clutchpoints.com/clippers-news-rajon-rondo-speaks-out-after-clippers-debut-vs-lakers" but maybe I'm wrong?

Is there a way to troubleshoot this? Thanks!

**Comment by ttscoff** [comment]
Pretty sure that extension is broken. It used the longurl.org API to expand shortened links, and that API is dead. I'll look into it, though, as you're correct, it _should_ be removing all query strings (if you have the option set, otherwise it's only looking for Google Analytics strings).

**Comment by ttscoff** [comment]
I think it _was_ working, I just had it set up to only clean non-GA query strings if you held down Option when clicking it. I made that an actual config option that will show up when you install it now. You can still force it with Option, regardless of the setting. Pushed an updated version to the repo, and the new download (v1.32) will be available [on my blog](https://brettterpstra.com/projects/bretts-popclip-extensions/) shortly.

Also removed the broken link expansion stuff.
