### ISSUE TITLE
Sum Extension - Error on Installing

### ISSUE THREAD

**Issue by mgguinne** [ttscoff/popclipextensions#8]
Hi Brett,

Great list of pop clip extensions, I heard about it on the automators podcast.

I just wanted to raise that the "Sum" extension gives me an error when I try to install it, your other ones appear to work correctly.

![image](https://user-images.githubusercontent.com/10627164/136710908-058bb4d0-6a63-43b8-a436-3ca20103ef61.png)

Model Identifier: MacBookAir10,1 (M1)
Memory: 16 GB
System Firmware Version: 6723.140.2
OS Loader Version: 6723.140.2
System Version: macOS 11.6 (20G165)
Kernel Version: Darwin 20.6.0
System Integrity Protection: Enabled

**Comment by ttscoff** [comment]
Fixed this in the latest update (1.34). Source is updated in this repo, and the zipped version is available for download [on my blog](https://brettterpstra.com/projects/bretts-popclip-extensions/).
